//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direction
    {
        public int Direction_id { get; set; }
        public int Specialty_id { get; set; }
        public int Patient_id { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
