//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int Doctor_id { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Patronymic { get; set; }
        public int Flor_id { get; set; }
        public System.DateTime DataOfBirth { get; set; }
        public int Specialty_id { get; set; }
        public int Cabinet { get; set; }
        public string Passport { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int Polyclinic_id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }

        public string AllNAme
        {
            get
            {
                string _Name = Name + " " + Lastname + " " + Patronymic;
                return _Name;
            }
        }

        public virtual Floor Floor { get; set; }
        public virtual Polyclinic Polyclinic { get; set; }
        public virtual Specialty Specialty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
